import type { DayWorkout, WorkoutType } from "@/types";

import { TOTAL_WEEKS } from "@/lib/constants";

function day(
  dayLabel: string,
  title: string,
  type: WorkoutType,
  description: string,
  durationLabel: string,
  detail?: string,
): DayWorkout {
  const base: DayWorkout = { dayLabel, title, type, description, durationLabel };
  if (detail) base.detail = detail;
  return base;
}

/** Ma → Zo, week 1 … TOTAL_WEEKS */
export const TRAINING_WEEKS: DayWorkout[][] = [
  // ─── Week 1 ─────────────────────────────────────────────────────────────
  [
    day(
      "Ma",
      "Mobiliteit & wandeling",
      "rest",
      "Actief herstel: wandelen + heupen/ enkels losmaken.",
      "30–40 min",
      "5–10 min easy wandelen, daarna dynamic mobility: leg swings, cat-cow, world’s greatest stretch. Geen vermoeidheid — voorbereiden op dinsdag.",
    ),
    day(
      "Di",
      "4 × 400 m (rustig tempo)",
      "run",
      "Korte repetities om het lichaam te laten wennen aan versnelling.",
      "35–45 min",
      "Opwarming: 10–15 min rustig joggen + strides.\n\nHoofddeel: 4 × 400 m op rustig tempo (ongeveer 5K-pace + 20–40 s per rep). Wandel/jog rust tussen reps: 90–120 s.\n\nTechniek: rechte rug, korte contacttijd, rustige schouders. Afkoelen: 8 min joggen.\n\nDoel: aerobe prikkel zonder ‘race-gevoel’.",
    ),
    day(
      "Wo",
      "Yoga / foam roll",
      "rest",
      "Herstel: flexibiliteit en tissue quality.",
      "25–35 min",
      "Foam roll: kuiten, quads, IT-band (voorzichtig), thoracic extension op roller. Optioneel: 15 min zachte yoga flow thuis.",
    ),
    day(
      "Do",
      "3 km rustig",
      "run",
      "Praattempo / zone 2 — duur opbouwen.",
      "22–28 min",
      "Continu lopen. Hartslag: je moet in volledige zinnen kunnen praten. Vlak terrein kiezen. Na afloop: 5 min wandelen + lichte rekking quadriceps/hamstrings.",
    ),
    day(
      "Vr",
      "Core & heupstabiliteit",
      "gym",
      "Korte krachtsessie zonder zware vermoeidheid voor het weekend.",
      "30–35 min",
      "3 rondes, rustig tempo:\n• Dead bug 3 × 10/side\n• Side plank 3 × 30 s/side\n• Hip thrust met eigen lichaam of lichte DB 3 × 12\n• Calf raises 2 × 15\n• Bird dog 3 × 8/side\n\nGeen failure — morgen staat het circuit.",
    ),
    day(
      "Za",
      "Circuit: squats, lunges, push-ups",
      "gym",
      "Full body met eigen lichaam — kracht-uithoudingsvermogen.",
      "35–45 min",
      "3–4 rondes, 60 s rust tussen rondes:\n• Bodyweight squat × 15 (diep, knieën naar buiten)\n• Reverse lunge × 10/been\n• Push-ups × 10–15 (knieën oké)\n• Plank 40 s\n\nFocus: bewegingskwaliteit > snelheid. Noteer hoe je je voelde voor volgende week.",
    ),
    day(
      "Zo",
      "Rust",
      "rest",
      "Geen training — herstel absorberen.",
      "—",
      "Optioneel: wandeling in zone 1. Hydratie en slaap prioriteit.",
    ),
  ],
  // ─── Week 2 ─────────────────────────────────────────────────────────────
  [
    day(
      "Ma",
      "Wandelen zone 1",
      "rest",
      "30–40 min actief herstel.",
      "30–40 min",
      "Rustige wandeling. Geen hardlopen vandaag.",
    ),
    day(
      "Di",
      "5 × 400 m",
      "run",
      "Iets meer volume dan week 1.",
      "40–48 min",
      "Opwarming 12 min + 4 strides.\n\n5 × 400 m, zelfde rust 90–120 s. Tempo iets strakker dan vorige week maar nog gecontroleerd — RPE ca. 6–7/10.\n\nAfkoelen 8 min.",
    ),
    day(
      "Wo",
      "Foam roll + mobiliteit",
      "rest",
      "Herstel tussen twee hardloopdagen in.",
      "25 min",
      "Rug, heupen, enkels. Optioneel lichte mobiliteit drills.",
    ),
    day(
      "Do",
      "3,5 km rustig",
      "run",
      "Zone 2 — iets langer dan week 1.",
      "26–32 min",
      "Steady state. Geen acceleraties. Let op voetlanding en cadans (lichtjes kortere passen is oké).",
    ),
    day(
      "Vr",
      "Core-circuit",
      "gym",
      "Plank-varianten en anti-rotatie.",
      "28 min",
      "3 rondes:\n• Plank 45 s\n• Side plank dips 8/side\n• Pallof press 12/side (licht elastiek of kabel)\n• Dead bug 10/side",
    ),
    day(
      "Za",
      "Circuit + core",
      "gym",
      "Zelfde basis als week 1 + extra coreblok.",
      "40–50 min",
      "4 rondes:\n• Squat × 15\n• Lunge × 10/been\n• Push-up × 12\n• Superman 12\n• Bicycle crunch 20\n\n60 s rust tussen rondes. Laatste ronde: plank 60 s finisher.",
    ),
    day("Zo", "Rust", "rest", "Volledige rust.", "—", undefined),
  ],
  // ─── Week 3 ─────────────────────────────────────────────────────────────
  [
    day(
      "Ma",
      "Licht joggen",
      "run",
      "20 min heel rustig — bloedstroming.",
      "20 min",
      "Alleen als je fris bent; anders wandelen. Geen schema-druk.",
    ),
    day(
      "Di",
      "6 × 400 m",
      "run",
      "Volume-interval op gecontroleerd tempo.",
      "42–52 min",
      "Opwarming 12 min.\n\n6 × 400 m, 90 s rust (actief: heel licht joggen mag als je herstelt snel). Tempo: gelijk verdeeld — geen ‘kick’ op de laatste rep tenzij je nog heel fris bent.\n\nAfkoelen 8 min + kuiten stretchen.",
    ),
    day("Wo", "Rust", "rest", "Geplande hersteldag.", "—", undefined),
    day(
      "Do",
      "4 km rustig",
      "run",
      "Duur in zone 2.",
      "28–35 min",
      "Blijf in praattempo. Optioneel: laatste km iets opener cadans (niet sneller!), om ritme te voelen.",
    ),
    day(
      "Vr",
      "Benen onderhoud",
      "gym",
      "Split squat, step-ups — licht.",
      "30 min",
      "Bulgarian split squat 3 × 8/been (lichte DB oké)\n• Step-up 3 × 10/been\n• Nordics alleen als je ervaring hebt — anders hamstring walk-outs\n\nGeen zware eccentric die hardlopen morgen beïnvloedt.",
    ),
    day(
      "Za",
      "3 rondes: 400 m + 15 squats + 10 push-ups",
      "combo",
      "Eerste vorm van run-strength combinatie.",
      "35–45 min",
      "Opwarming: 8 min jog + mobiliteit.\n\n3 rondes:\n• 400 m run (tempo: stevig maar geen sprint)\n• 15 air squats (diepte, knieën trackten over tenen)\n• 10 push-ups\n\nRust tussen rondes: 2–3 min wandelen tot adem rustig.\n\nDoel: transities voelen — HYROX-relevant zonder race-intensiteit.",
    ),
    day("Zo", "Rust / wandeling", "rest", "Optioneel 30 min wandelen.", "—", undefined),
  ],
  // ─── Week 4 ─────────────────────────────────────────────────────────────
  [
    day(
      "Ma",
      "Dynamic warm-up routine",
      "gym",
      "Bewegingsvoorbereiding voor langere reps.",
      "20 min",
      "A-skips, B-skips, walking lunges, arm circles — gebruik als standalone of voor morgen voorbereiden.",
    ),
    day(
      "Di",
      "4 × 600 m",
      "run",
      "Langere reps — aerobe kracht.",
      "45–55 min",
      "Opwarming 12 min + 3 strides.\n\n4 × 600 m, rust 2 min (wandelen). Tempo: iets onder 10K-achtig gevoel; ademhaling diep maar gecontroleerd.\n\nFocus: gelijke splits per rep (bijv. alle rondes ±5 s).\n\nAfkoelen 10 min.",
    ),
    day("Wo", "Rust / zwem licht", "rest", "Actief herstel optioneel.", "—", "Zwemmen 20 min heel rustig of wandelen."),
    day(
      "Do",
      "4,5 km rustig",
      "run",
      "Zone 2 — duur opbouwen richting 5 km.",
      "32–38 min",
      "Continu. Geen muziek-te-hard tempo — houd conversatie-tempo aan.",
    ),
    day(
      "Vr",
      "Upper body onderhoud",
      "gym",
      "Rug/schouders zonder vermoeide benen.",
      "35 min",
      "DB row 3 × 12\n• Face pull of band pull-apart 3 × 15\n• Push-up variation 3 × 10\n• Dead hang 3 × max tijd (niet tot failure)",
    ),
    day(
      "Za",
      "Circuit",
      "gym",
      "Full body — iets meer volume dan week 1–2.",
      "40–50 min",
      "4 rondes, 75 s rust:\n• Squat jump (of squat) × 12\n• Walking lunge × 12 stappen\n• Push-up × 12\n• Mountain climber × 20\n• Plank shoulder tap × 16 totaal",
    ),
    day("Zo", "Rust", "rest", "—", "—", undefined),
  ],
  // ─── Week 5 ─────────────────────────────────────────────────────────────
  [
    day("Ma", "Mobiliteit heupen", "rest", "15 min + wandeling.", "25 min", undefined),
    day(
      "Di",
      "5 × 600 m",
      "run",
      "Middenlange intervallen.",
      "48–58 min",
      "Opwarming 12 min.\n\n5 × 600 m, 2 min rust. Houd splits strak; laatste rep mag iets opener als techniek goed blijft.\n\nAfkoelen 10 min.",
    ),
    day("Wo", "Rust", "rest", "—", "—", undefined),
    day(
      "Do",
      "5 km rustig",
      "run",
      "Belangrijke duurprikkel richting 5 km-comfort.",
      "35–42 min",
      "Volledige 5 km in zone 2. Dit is een referentiesessie: noteer tijd en gevoel (geen race vandaag).\n\nNa afloop: hydratatie + lichte maaltijd met eiwitten.",
    ),
    day(
      "Vr",
      "Core + rotatie",
      "gym",
      "Voorbereiding op zaterdag HYROX-intro.",
      "28 min",
      "Landmine of DB rotational press 3 × 8/side\n• Anti-rotation walkout 3 × 10\n• Plank drag (licht gewicht) 3 × 8/side",
    ),
    day(
      "Za",
      "Lichte HYROX-intro",
      "station",
      "Kennismaking met 2–3 klassieke bewegingen.",
      "40–50 min",
      "Kies 2–3 stations (bijv. SkiErg 3 × 250 m rustig, Row 3 × 250 m, Wall ball 3 × 10 met lichte bal).\n\nDoel: vorm en ademhaling — geen maximale inspanning. Wissel met partner af als duo.\n\nSluit af met 5 min mobiliteit.",
    ),
    day("Zo", "Rust", "rest", "—", "—", undefined),
  ],
  // ─── Week 6 ─────────────────────────────────────────────────────────────
  [
    day("Ma", "Wandelen", "rest", "Zone 1.", "30 min", undefined),
    day(
      "Di",
      "6 × 600 m",
      "run",
      "Hoogste intervalvolume in fase 1.",
      "50–62 min",
      "Opwarming 15 min.\n\n6 × 600 m, 2–2,5 min rust. Als je afvalt in kwaliteit na rep 4: stop bij 5 en noteer voor volgende cyclus.\n\nAfkoelen 10 min.",
    ),
    day("Wo", "Rust", "rest", "—", "—", undefined),
    day(
      "Do",
      "5 km",
      "run",
      "Steady — mag iets opener dan vorige 5 km als je fris bent.",
      "34–40 min",
      "Blijf in controle. Geen finish-sprint vandaag.",
    ),
    day(
      "Vr",
      "Lichte techniek",
      "station",
      "Korte techniekblokken.",
      "30 min",
      "SkiErg 2 × 3 min techniek\n• Row 2 × 3 min techniek\n\nAlleen vorm — geen test.",
    ),
    day(
      "Za",
      "4 rondes circuit",
      "combo",
      "Run + bodyweight — volume opbouwen.",
      "45–55 min",
      "4 rondes:\n• 500 m run (tempo: stevig)\n• 12 squats\n• 8 burpees (stap-in toegestaan)\n• 30 s plank\n\nRust 2–3 min tussen rondes. Focus adem: rustig uitademen in burpees.",
    ),
    day("Zo", "Rust", "rest", "—", "—", undefined),
  ],
  // ─── Week 7 — taper (Za/Zo rust) ─────────────────────────────────────────
  [
    day(
      "Ma",
      "Mobiliteit",
      "rest",
      "Heupen, enkels, thoracic — klaar voor taper-week.",
      "20 min",
      "Geen hardlopen. Leg swings, cat-cow, ankle rocks.",
    ),
    day(
      "Di",
      "3 × 400 m (licht)",
      "run",
      "Laatste scherpe prikkel vóór volledige rust.",
      "28–35 min",
      "Opwarming 10 min.\n\n3 × 400 m op licht tempo (RPE 5–6). 2 min rust.\n\nAfkoelen 8 min.",
    ),
    day("Wo", "Rust", "rest", "—", "—", undefined),
    day(
      "Do",
      "3 km rustig",
      "run",
      "Bloedstroming, geen vermoeidheid.",
      "18–24 min",
      "Praattempo. Vlak terrein.",
    ),
    day(
      "Vr",
      "Rust — voorbereiding",
      "rest",
      "Checklist Maastrichts Mooiste (week 8).",
      "—",
      "Starttijd, kleding, ontbijt, route naar start. Geen nieuwe schoenen.",
    ),
    day("Za", "Rust", "rest", "Volledige rust.", "—", undefined),
    day("Zo", "Rust", "rest", "Volledige rust.", "—", undefined),
  ],
  // ─── Week 8 — Maastrichts Mooiste 5 km ───────────────────────────────────
  [
    day(
      "Ma",
      "Korte run ①",
      "run",
      "Eerste van twee korte runs vóór de 5 km.",
      "18–22 min",
      "Max. 20 min loslopen in zone 2. Geen tempo. Doel: ritme voelen, benen wakker.",
    ),
    day(
      "Di",
      "Korte run ② + strides",
      "run",
      "Tweede korte run — lichte neuromusculaire prikkel.",
      "18–25 min",
      "12–15 min jog + 4–6 × 80–100 m strides @ comfortabel snel (niet sprint).\n\nAfkoelen: 5 min wandelen.",
    ),
    day("Wo", "Rust", "rest", "—", "—", undefined),
    day(
      "Do",
      "Mobiliteit & activatie",
      "gym",
      "Heupscharnier, schouders, core — geen vermoeidheid.",
      "25 min",
      "World’s greatest stretch, 90/90 heupen, shoulder CARs, dead bug 2 × 8.",
    ),
    day(
      "Vr",
      "Rust — voor race",
      "rest",
      "Morgen optioneel; zondag Maastrichts Mooiste.",
      "—",
      "Hydratie, vroeg slapen, rustige maaltijd. Geen alcohol.",
    ),
    day(
      "Za",
      "Optioneel: ultralichte activatie",
      "rest",
      "Alleen als je dit altijd doet — anders volledige rust.",
      "0–12 min",
      "Max. 8 min jog + mobiliteit. Stop als je ook maar iets van zwaarte voelt.",
    ),
    day(
      "Zo",
      "Maastrichts Mooiste — 5 km",
      "race",
      "5 km — geniet van het event!",
      "~25–40 min",
      "Race day:\n• Vertrouwde warming-up (10–15 min jog + strides)\n• Start gecontroleerd — eerste km niet te snel\n• Na finish: lopen uit, drinken, voeding binnen 30 min\n\nDit sluit fase 1 af — daarna bouw je verder richting HYROX-fase 2.",
    ),
  ],
  // ─── Week 9 — Fase 2 start ───────────────────────────────────────────────
  [
    day("Ma", "Herstel / wandelen", "rest", "Na 5 km-event: licht actief.", "30 min", undefined),
    day(
      "Di",
      "4 × 800 m",
      "run",
      "Langere reps — nieuwe fase.",
      "48–58 min",
      "Opwarming 12 min + strides.\n\n4 × 800 m, 2–2,5 min rust (wandelen). Tempo: gecontroleerd — RPE 7 max.\n\nGelijke splits. Afkoelen 10 min.",
    ),
    day("Wo", "Rust", "rest", "—", "—", undefined),
    day(
      "Do",
      "HYROX-klas",
      "class",
      "Vaste groepsles — techniek & format.",
      "55–65 min",
      "Volg de instructeur. Focus: transities tussen bewegingen, ademhaling, partnercommunicatie.\n\nNeem notities welke stations zwaar aanvoelen — dat wordt input voor zaterdag.",
    ),
    day(
      "Vr",
      "Core + schouders",
      "gym",
      "Ondersteuning voor wall balls / sled.",
      "32 min",
      "Landmine press 3 × 10\n• Face pull 3 × 15\n• Pallof 3 × 10/side\n• Dead hang 3 × 20–30 s",
    ),
    day(
      "Za",
      "3 rondes: 800 m + lunges + burpees",
      "combo",
      "Schema-zaterdag — eerste HYROX-achtige blok.",
      "45–55 min",
      "Opwarming 10 min jog.\n\n3 rondes:\n• 800 m run (tempo: stevig, geen sprint)\n• Walking lunges × 20 totaal (afwisselen met partner mag)\n• Burpees × 10 (stap-in toegestaan)\n\n2,5–3 min rust tussen rondes. Houd techniek strak als je moe wordt.",
    ),
    day("Zo", "Rust", "rest", "—", "—", undefined),
  ],
  // ─── Week 10 ────────────────────────────────────────────────────────────
  [
    day("Ma", "Mobiliteit", "rest", "Heupen & thoracic.", "20 min", undefined),
    day(
      "Di",
      "5 × 800 m",
      "run",
      "Meer volume op 800 m.",
      "52–64 min",
      "Opwarming 15 min.\n\n5 × 800 m, 2 min rust. Als kwaliteit zakt: stop bij 4 reps en bouw volgende week verder.\n\nAfkoelen 10 min.",
    ),
    day("Wo", "Rust", "rest", "—", "—", undefined),
    day(
      "Do",
      "HYROX-klas",
      "class",
      "Vaste les — bouw consistentie.",
      "55–65 min",
      "Zelfde intentie als week 9: techniek > ego. Vraag feedback op wall ball depth.",
    ),
    day(
      "Vr",
      "Benen onderhoud",
      "gym",
      "Geen zware eccentric voor zaterdag.",
      "28 min",
      "Goblet squat 3 × 10\n• Step-down 3 × 8/been\n• Calf raises 3 × 15",
    ),
    day(
      "Za",
      "4 rondes: 800 m + lunges + burpees",
      "combo",
      "Meer rondes — iets meer volume.",
      "50–60 min",
      "4 rondes, zelfde structuur als week 9.\n\nRust 2–2,5 min tussen rondes. Noteer tijd per 800 m ( grove notitie is genoeg).",
    ),
    day("Zo", "Rust", "rest", "—", "—", undefined),
  ],
  // ─── Week 11 ────────────────────────────────────────────────────────────
  [
    day("Ma", "Wandelen", "rest", "Zone 1.", "30 min", undefined),
    day(
      "Di",
      "4 × 1 km",
      "run",
      "Kilometer-reps — aerobe power.",
      "50–62 min",
      "Opwarming 15 min.\n\n4 × 1000 m, rust 2–3 min (wandelen/jog). Tempo: ‘comfortabel hard’ — geen 5K race vandaag.\n\nFocus: gelijke kilometer-splits.\n\nAfkoelen 10 min.",
    ),
    day("Wo", "Rust", "rest", "—", "—", undefined),
    day(
      "Do",
      "HYROX-klas",
      "class",
      "Techniek onder vermoeidheid oefenen.",
      "55–65 min",
      "Let op adem in wall balls en row — dat bepaalt je latere run-legs.",
    ),
    day(
      "Vr",
      "Pull + brace",
      "gym",
      "Rugsterkte voor sled pull / row.",
      "35 min",
      "Ring row of cable row 4 × 10\n• RDL licht 3 × 10\n• Plank drag 3 × 8",
    ),
    day(
      "Za",
      "4 rondes + iets zwaarder",
      "combo",
      "Zelfde format, zwaardere variant waar veilig.",
      "55–65 min",
      "4 rondes:\n• 800 m run\n• Lunges met lichte DB of sandbag (als beschikbaar) × 16\n• Burpees × 12\n\nAlleen zwaarder als techniek strak blijft. Anders: week 10-gewicht.",
    ),
    day("Zo", "Rust", "rest", "—", "—", undefined),
  ],
  // ─── Week 12 ────────────────────────────────────────────────────────────
  [
    day("Ma", "Rust / yoga", "rest", "Optioneel licht.", "20 min", undefined),
    day(
      "Di",
      "5 × 1 km",
      "run",
      "Top-volume kilometerblok in fase 2.",
      "55–70 min",
      "Opwarming 15 min.\n\n5 × 1000 m, 2,5–3 min rust. Stop bij technische breakdown (heup drop, knie valgus).\n\nAfkoelen 10 min.",
    ),
    day("Wo", "Rust", "rest", "—", "—", undefined),
    day(
      "Do",
      "HYROX-klas",
      "class",
      "Vaste les.",
      "55–65 min",
      "Mentale note: welke station voelt als ‘jouw’ zwakte? Train die 1× extra in open gym als kan.",
    ),
    day(
      "Vr",
      "Sled prep (licht)",
      "station",
      "Techniek sled push/pull zonder vermoeidheid.",
      "30 min",
      "Alleen als faciliteit open is — anders hip thrust + plank.\n\nSled: lage romp, korte passes — blijf rustig uitademen (niet je adem blokkeren).",
    ),
    day(
      "Za",
      "5 rondes circuit",
      "combo",
      "5 rondes — meer densiteit.",
      "55–70 min",
      "5 rondes:\n• 600 m run\n• 12 squats\n• 10 burpees\n• 30 s plank\n\nRust 2 min. Als je >75 min wordt: schrap 1 ronde — kwaliteit voorop.",
    ),
    day("Zo", "Rust", "rest", "—", "—", undefined),
  ],
  // ─── Week 13 ────────────────────────────────────────────────────────────
  [
    day("Ma", "Mobiliteit", "rest", "—", "20 min", undefined),
    day(
      "Di",
      "Intervallen (mix)",
      "run",
      "Variatie: 6 × 400 m + 2 × 800 m OF coach-voorstel.",
      "50–65 min",
      "Kies één schema:\nA) 6 × 400 m (90 s rust) + 2 × 800 m (3 min rust)\nB) 3 × (600 + 400) met 3 min tussen sets\n\nDoel: schakelen tussen snelheid en aerobe kracht. Blijf binnen RPE 8.",
    ),
    day("Wo", "Rust", "rest", "—", "—", undefined),
    day(
      "Do",
      "HYROX-klas",
      "class",
      "Vaste les.",
      "55–65 min",
      "Vraag expliciet om feedback op transities (run → station mindset).",
    ),
    day(
      "Vr",
      "Techniek stations",
      "station",
      "2 stations diep — geen metcon.",
      "35 min",
      "SkiErg 4 × 2 min techniek\n• Wall ball 4 × 12 (lichte bal)\n\nStop vóór vermoeidheid.",
    ),
    day(
      "Za",
      "Mini-HYROX (4–5 stations)",
      "combo",
      "Korte race-sim — geen volledige afstand.",
      "60–80 min",
      "Met partner: kies 4–5 stations + korte run-secties (totaal ±25–35 min werk).\n\nVoorbeeld: 3 × (1 km + 1 station) + 2 extra stations.\n\nDoel: flow en communicatie — geen PR vandaag.",
    ),
    day("Zo", "Rust", "rest", "—", "—", undefined),
  ],
  // ─── Week 14 — deload fase 2 ─────────────────────────────────────────────
  [
    day("Ma", "Rust", "rest", "—", "—", undefined),
    day(
      "Di",
      "3 × 800 m",
      "run",
      "Deload: minder reps, frisse benen.",
      "38–45 min",
      "Opwarming 12 min.\n\n3 × 800 m, 2,5 min rust. Tempo: rustiger dan week 12–13.\n\nAfkoelen 8 min.",
    ),
    day("Wo", "Rust", "rest", "—", "—", undefined),
    day(
      "Do",
      "Lichte HYROX-klas",
      "class",
      "Herstelweek — instructeur volgen, minder volume.",
      "45–55 min",
      "Geen competitie met jezelf — techniek en ritme.",
    ),
    day(
      "Vr",
      "Mobiliteit + wandelen",
      "rest",
      "Actief herstel.",
      "35 min",
      "Lichte wandeling + heup flexors stretchen.",
    ),
    day(
      "Za",
      "Korte workout",
      "combo",
      "2–3 rondes licht — geen deep fatigue.",
      "30–40 min",
      "2–3 rondes:\n• 400 m easy\n• 10 squats\n• 6 burpees\n\nRuim rust. Morgen weer opbouwen richting fase 3.",
    ),
    day("Zo", "Rust", "rest", "—", "—", undefined),
  ],
  // ─── Week 15 — Fase 3 ────────────────────────────────────────────────────
  [
    day("Ma", "Wandelen", "rest", "—", "30 min", undefined),
    day(
      "Di",
      "4 × 1 km",
      "run",
      "Start fase 3 — scherpe kilometerblokken.",
      "50–62 min",
      "Opwarming 15 min.\n\n4 × 1000 m, 2–3 min rust. RPE 7–8.\n\nNoteer splits. Afkoelen 10 min.",
    ),
    day("Wo", "Rust", "rest", "—", "—", undefined),
    day(
      "Do",
      "HYROX-klas",
      "class",
      "Vaste les onder hogere weekbelasting.",
      "55–65 min",
      "Focus: consistente bewegingskwaliteit — zelfs als instructie tempo hoog is.",
    ),
    day(
      "Vr",
      "Compromised primer",
      "combo",
      "Korte run na lichte stationprikkel.",
      "35 min",
      "3 rondes:\n• Wall ball × 15 (lichte bal)\n• 600 m run direct starten\n\nRust 3 min tussen rondes. Doel: ‘zware benen start’ zonder volume van zaterdag.",
    ),
    day(
      "Za",
      "HYROX-sim ±50%",
      "combo",
      "Halve tot tweederde race-intensiteit — tijd en energie naar eigen niveau.",
      "70–100 min",
      "Met partner: bouw een parcours dat ongeveer 50% van race-gevoel geeft (afstanden schalen).\n\nVoorbeeld: 4–5 km run totaal + 4 stations op race-gewicht of 1 stap lichter.\n\nHydratie en voeding zoals race — mini dry-run.",
    ),
    day("Zo", "Rust", "rest", "—", "—", undefined),
  ],
  // ─── Week 16 ────────────────────────────────────────────────────────────
  [
    day("Ma", "Mobiliteit", "rest", "—", "20 min", undefined),
    day(
      "Di",
      "5 × 1 km",
      "run",
      "Meer kilometer-volume.",
      "55–72 min",
      "Opwarming 15 min.\n\n5 × 1000 m, 2,5–3 min rust. Houd techniek — knie lift, armswing relaxed.\n\nAfkoelen 10 min.",
    ),
    day("Wo", "Rust", "rest", "—", "—", undefined),
    day(
      "Do",
      "HYROX-klas",
      "class",
      "Vaste les.",
      "55–65 min",
      "Let op hartslagherstel tussen blokken — dat is je race-sensor.",
    ),
    day(
      "Vr",
      "Upper + grip",
      "gym",
      "Farmers carry prep.",
      "35 min",
      "Farmers hold 4 × 40 m (licht)\n• Rowing brace 3 × 10\n• Hammer curl 3 × 10 (grip)",
    ),
    day(
      "Za",
      "HYROX-sim ±60%",
      "combo",
      "Iets langere / zwaardere sim dan week 15.",
      "80–110 min",
      "Zelfde structuur als 50%-sim maar:\n• +1 station of +1 km run totaal\n• stations dichter bij race-gewicht\n\nStop als techniek 2 rondes achter elkaar breekt.",
    ),
    day("Zo", "Rust", "rest", "—", "—", undefined),
  ],
  // ─── Week 17 ────────────────────────────────────────────────────────────
  [
    day("Ma", "Rust / wandelen", "rest", "—", "25 min", undefined),
    day(
      "Di",
      "4 × 1 km (sneller)",
      "run",
      "Zelfde reps — hogere intentie (alleen als fris).",
      "50–62 min",
      "4 × 1000 m. Vergelijk met week 15 — alleen sneller als RPE en techniek het toelaten.\n\n2,5–3 min rust. Geen sprint op laatste rep als je trillerig wordt.",
    ),
    day("Wo", "Rust", "rest", "—", "—", undefined),
    day(
      "Do",
      "HYROX-klas",
      "class",
      "Vaste les.",
      "55–65 min",
      "Mentale cue: ‘rustige handen, snelle benen’ bij run-secties in les.",
    ),
    day(
      "Vr",
      "Ski + row techniek",
      "station",
      "Korte dubbel — geen PR.",
      "30 min",
      "Ski 3 × 3 min / Row 3 × 3 min — afwisselen, focus stroke rate en relaxed grip.",
    ),
    day(
      "Za",
      "HYROX-sim ±70%",
      "combo",
      "Langere sim — dichter bij race.",
      "90–120 min",
      "Opbouw richting 70% race-gevoel: meer stations of langere run-blokken.\n\nEet 2–3 uur van tevoren licht verteerbaar. Neem race-nutrition mee (zoals op wedstrijd).",
    ),
    day("Zo", "Rust", "rest", "—", "—", undefined),
  ],
  // ─── Week 18 ────────────────────────────────────────────────────────────
  [
    day("Ma", "Mobiliteit", "rest", "—", "20 min", undefined),
    day(
      "Di",
      "Intervallen (schakelen)",
      "run",
      "3–4 × (600 m hard / 400 m easy) of klassieke 8 × 400.",
      "48–60 min",
      "Kies schema dat aansluit op les-locatie en energie.\n\nDoel: schakelen tussen snelheid en herstel — HYROX-run-gevoel.",
    ),
    day("Wo", "Rust", "rest", "—", "—", undefined),
    day(
      "Do",
      "HYROX-klas",
      "class",
      "Vaste les.",
      "55–65 min",
      "Als je moe bent van zaterdag: meld het — schaal in overleg.",
    ),
    day(
      "Vr",
      "Wall ball + run",
      "combo",
      "Korte compromised block.",
      "32 min",
      "4 rondes: 20 wall balls (lichte bal) + 500 m run — 2 min rust.",
    ),
    day(
      "Za",
      "HYROX-sim ±80%",
      "combo",
      "Zwaar weekendblok — plan herstel zondag.",
      "100–130 min",
      "80% sim: bijna volledige structuur maar iets korter op run of 1 station minder.\n\nPartner: oefen expliciet ‘wie gaat voor’ bij gecombineerde stukken.\n\nHydratie-agressiever dan normaal (elektrolyten).",
    ),
    day("Zo", "Rust / wandelen", "rest", "Herstel zaterdag.", "30–45 min", "Lichte wandeling, veel vocht."),
  ],
  // ─── Week 19 ────────────────────────────────────────────────────────────
  [
    day("Ma", "Rust", "rest", "—", "—", undefined),
    day(
      "Di",
      "Kort + snel",
      "run",
      "10 × 200 m snel met lange rust OF 5 × 300 m.",
      "40–48 min",
      "Opwarming uitgebreid (15 min).\n\nHoofddeel: snelheidssensatie zonder grote belasting — RPE 8 op reps, volledige rust (2 min) zodat kwaliteit hoog blijft.\n\nAfkoelen 10 min.",
    ),
    day("Wo", "Rust", "rest", "—", "—", undefined),
    day(
      "Do",
      "HYROX-klas",
      "class",
      "Laatste zware lesweek vóór taper — nog steeds techniek.",
      "55–65 min",
      "Geen nieuwe experimenten vandaag.",
    ),
    day(
      "Vr",
      "Mobiliteit + core",
      "gym",
      "Licht — voorbereiding op zaterdag.",
      "25 min",
      "Alleen activeren, niet vermoeien.",
    ),
    day(
      "Za",
      "HYROX-sim ±90%",
      "combo",
      "Laatste grote sim — bijna race.",
      "110–140 min",
      "90%: bijna volledige race-structuur. Alleen inkorten als herstel risico loopt.\n\nNa afloop: noteer nutrition, wat werkte, wat niet. Dit is jullie race-debrief template.",
    ),
    day("Zo", "Rust", "rest", "—", "—", undefined),
  ],
  // ─── Week 20 — taper ─────────────────────────────────────────────────────
  [
    day("Ma", "Wandelen", "rest", "—", "30 min", undefined),
    day(
      "Di",
      "4 × 800 m",
      "run",
      "Taper: middel volume, geen grind.",
      "42–50 min",
      "Opwarming 12 min.\n\n4 × 800 m, 2 min rust — tempo iets onder vorige weken.\n\nAfkoelen 10 min.",
    ),
    day("Wo", "Rust", "rest", "—", "—", undefined),
    day(
      "Do",
      "HYROX-klas (licht)",
      "class",
      "Lage intensiteit — gevoel & routine.",
      "45–55 min",
      "Focus op smoothness. Geen nieuwe schoenen of gear.",
    ),
    day(
      "Vr",
      "Rust",
      "rest",
      "—",
      "—",
      "Mentale visualisatie: start, eerste station, transitie naar partner.",
    ),
    day(
      "Za",
      "HYROX-sim ±60%",
      "combo",
      "Afkaderen — geen nieuwe records.",
      "70–90 min",
      "60% alleen om ritme te voelen — stop ruim op tijd. Avond: vroeg slapen.",
    ),
    day("Zo", "Rust", "rest", "—", "—", undefined),
  ],
  // ─── Week 21 — taper ─────────────────────────────────────────────────────
  [
    day("Ma", "Mobiliteit", "rest", "—", "20 min", undefined),
    day(
      "Di",
      "Korte intervallen",
      "run",
      "6 × 200 m licht snel OF 5 × 300 m comfortabel.",
      "35–42 min",
      "Neuromusculaire frisheid — geen zuur. RPE 6–7.",
    ),
    day("Wo", "Rust", "rest", "—", "—", undefined),
    day(
      "Do",
      "Lichte HYROX-klas",
      "class",
      "Activatie — geen vermoeidheid.",
      "40–50 min",
      "Laatste les voor race: geniet, adem, routine.",
    ),
    day(
      "Vr",
      "Rust — checklist",
      "rest",
      "Race-weekend voorbereiden.",
      "—",
      "Spullen, reis, maaltijden, starttijden MECC.",
    ),
    day(
      "Za",
      "Korte workout",
      "combo",
      "2 rondes licht — optioneel.",
      "25–35 min",
      "2 rondes: 400 m easy + 10 wall balls licht + 6 burpees. Of volledig rust.",
    ),
    day("Zo", "Rust", "rest", "—", "—", undefined),
  ],
  // ─── Week 22 — race week ─────────────────────────────────────────────────
  [
    day(
      "Ma",
      "Rust / wandelen",
      "rest",
      "Rustige week — race in weekend.",
      "25 min",
      undefined,
    ),
    day(
      "Di",
      "20 min loslopen",
      "run",
      "Zeer licht — bloedstroming.",
      "20 min",
      "Zone 1–2. Geen strides nodig tenzij je daarvan frisser wordt.",
    ),
    day("Wo", "Rust", "rest", "—", "—", undefined),
    day(
      "Do",
      "Lichte activatie",
      "combo",
      "Beweging zonder vermoeidheid — ritme voelen.",
      "25–30 min",
      "10 min jog\n• mobiliteit\n• 2 × 6 wall balls (licht)\n• 2 × 100 m strides heel comfortabel\n\nStop ruim.",
    ),
    day(
      "Vr",
      "Rust",
      "rest",
      "—",
      "—",
      "Hydratie, normale maaltijden, geen nieuwe voeding testen.",
    ),
    day(
      "Za",
      "Optioneel: shakeout",
      "run",
      "Alleen vaste routine — max 15 min.",
      "0–15 min",
      "Sommigen willen kort bewegen; anderen volledig rust — kies wat jullie altijd doen voor races.",
    ),
    day(
      "Zo",
      "HYROX race — MECC Maastricht",
      "race",
      "Race day — jullie moment.",
      "~90 min+",
      "Race week:\n• Check heat-tijd en bagage-regels MECC\n• Start rustig — eerste run-sectie niet te hard\n• Transities met partner afgestemd\n• Na finish: hersteldrank + eiwit\n\n🔥 Succes — het werk zit in de weken ervoor; vandaag is uitvoeren.",
    ),
  ],
];

if (TRAINING_WEEKS.length !== TOTAL_WEEKS) {
  throw new Error(
    `TRAINING_WEEKS: verwacht ${TOTAL_WEEKS} weken, kreeg ${TRAINING_WEEKS.length}`,
  );
}
